
services:
  eureka-sv:
    build:
      context: ./eureka-sv
    ports:
      - "8761:8761"
    networks:
      - eureka-net

  users-server:
    build:
      context: ./users-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-sv
      - mysql
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/users_services?serverTimezone=UTC
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    networks:
      - eureka-net

  posts-server:
    build:
      context: ./posts-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-sv
      - mysql
    environment:
      - DB_URL=jdbc:mysql://mysql-s-2:3306/posts_services?serverTimezone=UTC
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    networks:
      - eureka-net

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: users_services
    ports:
      - "3306:3306"
    networks:
      - eureka-net
  mysql-s-2:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: posts_services   
    ports:
      - "3307:3306"  
    networks:
      - eureka-net    

networks:
  eureka-net:
    driver: bridge
