
services:
  eureka-sv:
    build:
      context: ./eureka-sv
    ports:
      - "8761:8761"
    networks:
      - eureka-net

  users-server:
    build:
      context: ./users-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-sv
      - mysql-db
    environment:
      - DB_URL=${DB_USERS_URL}
      - DB_USER=${DB_USERS_USER}
      - DB_PASS=${DB_USERS_PASS}
    networks:
      - eureka-net

  posts-server:
    build:
      context: ./posts-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-sv
      - mysql-db
    environment:
      - DB_URL=${DB_POSTS_URL}
      - DB_USER=${DB_POSTS_USER}
      - DB_PASS=${DB_POSTS_PASS}
    networks:
      - eureka-net

networks:
  eureka-net:
    driver: bridge
